name: Setup Node and install dependencies
description: Configure the Node.js runtime from .nvmrc and install npm dependencies.
inputs:
  cache-dependency-path:
    description: Optional path to the dependency lockfile used for caching
    required: false
    default: package-lock.json
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        cache: npm
        cache-dependency-path: ${{ inputs.cache-dependency-path }}

    - name: Install dependencies
      shell: bash
      run: npm ci

